### ISSUE TITLE
md文件无法正常预览

### ISSUE THREAD

**Issue by li9269391** [overnote/over-javascript#3]
写的文章很不错，只是不知道为什么您提交的 md 文件在 github 上无法预览？是怎么做到的呢，谢谢
![Snipaste_2023-02-03_11-00-32的副本](https://user-images.githubusercontent.com/10287877/216502456-60cc1c14-4152-43e3-87e8-e5e469fd5248.png)

**Comment by ruyuejun** [comment]
很抱歉，我一直都是自己在学习当笔记用了，没有关注github上的信息。不能显示是因为我限制了md的解析，我现在取消限定可以正常按照markdown格式浏览了
